# _config.yml
title: CropCart
description: >- # this means to ignore newlines until "baseurl:"
  From farm to your door.
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://crop-collections.github.io/cropcart2" # the base hostname & protocol for your site

source: docs
destination: _site

# Other configurations
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
