# _config.yml
title: My Jekyll Site
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome Jekyll site.
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://crop-collections.github.io/cropcart2" # the base hostname & protocol for your site

source: docs
destination: _site

# Other configurations
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
